name: Build and Push Docker Image

on:
  push:
    branches:
      - master  # Triggers the workflow when changes are pushed to the master branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Add your Docker Hub username as a secret in the repository settings
        password: ${{ secrets.DOCKER_PASSWORD }}  # Add your Docker Hub password as a secret in the repository settings

    - name: Build Docker image
      run: |
        docker build -t devasheesh22/wisdom-serv
