name: CI/CD Pipeline for Wisecow Application

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t devasheesh22/wisdom-server:v1 .

    - name: Push Docker image to Docker Hub
      run: |
        docker push devasheesh22/wisdom-server:v1

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'v1.21.2'

    - name: Authenticate to Kubernetes
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.K8S_SERVICE_ACCOUNT_KEY }}

    - name: Deploy to Kubernetes
      run: |
        kubectl set image deployment/wisdom-server wisdom-server=devasheesh22/wisdom-server:v1 --record
        kubectl rollout status deployment/wisdom-server

    # Example of environment variable usage
    - name: Set Kubernetes deployment status in environment
      run: |
        echo "DEPLOYMENT_STATUS=Deployment completed successfully" >> $GITHUB_ENV
